export const SeedData = [
  {
    full_name: 'John Snow',
    mobile_phone_number: '1234567890',
    email: 'JohnSnow@gmail.com',
    password: 'JohnSnow',
    nationality: 'Indian',
    isAdmin: false,
  },
  {
    full_name: 'John Cena',
    mobile_phone_number: '1234567890',
    email: 'JohnCena@gmail.com',
    password: 'JohnCena',
    nationality: 'American',
    isAdmin: false,
  },
  {
    full_name: 'Rick Sanchez',
    mobile_phone_number: '1234567890',
    email: 'RickSanchez@gmail.com',
    password: 'RickSanchez',
    nationality: 'Canadian',
    isAdmin: true,
  },
  {
    full_name: 'Enola Holmes',
    mobile_phone_number: '1234567890',
    email: 'EnolaHolmes@gmail.com',
    password: 'EnolaHolmes',
    nationality: 'British',
    isAdmin: false,
  },
  {
    full_name: 'Diana Prince',
    mobile_phone_number: '1234567890',
    email: 'DianaPrince@gmail.com',
    password: 'DianaPrince',
    nationality: 'Amazon',
    isAdmin: false,
  },
  {
    full_name: 'Lisa Simpson',
    mobile_phone_number: '1234567890',
    email: 'LisaSimpson@gmail.com',
    password: 'LisaSimpson',
    nationality: 'Springfield',
    isAdmin: true,
  },
];
